import './ui/styles.css'
import {seedPlaces,type SoundCategory,type SoundPlace} from './core/sound-place'
import {LocalSoundRepository} from './adapters/local-sound-repository'
import {BrowserRecorder} from './adapters/browser-recorder'
import {Spectrum} from './ui/spectrum'
const repo=new LocalSoundRepository(),recorder=new BrowserRecorder(),app=document.querySelector<HTMLDivElement>('#app')!;
let selected:SoundPlace=seedPlaces[0],pending={x:51,y:52},audioUrl:string|undefined,spectrum:Spectrum;
const places=()=>[...repo.list(),...seedPlaces];
function render(){app.innerHTML=`<main><header><a class="brand"><i></i>声场 <span>SONIC ATLAS</span></a><nav>探索 <b>我的采集</b><em>北京 · CHINA</em></nav><button class="add">＋ 标记声音</button></header><section class="hero"><div><p class="eyebrow">城市的每一次呼吸，都值得被听见</p><h1>聆听正在发生的<br/><strong>城市故事。</strong></h1><p class="intro">拾起一段声音，留在它发生的地方。<br/>它会成为这座城市的共同记忆。</p></div><div class="stats"><b>${places().length}</b><span>处声音标记</span><b>03:28</b><span>已收集时长</span></div></section><section class="map-shell"><div class="map-head"><span>北京 · 声音地图</span><small>点击地图的任意位置，放置新的声音标记</small><div class="legend"><i></i>有声音 <i></i>待采集</div></div><div class="map" id="map"><div class="roads"></div><div class="river"></div>${places().map(p=>`<button class="pin ${p.id===selected.id?'active':''}" data-id="${p.id}" style="left:${p.x}%;top:${p.y}%"><span>◉</span><label>${p.name}</label></button>`).join('')}<div class="cross c1"></div><div class="cross c2"></div></div></section><section class="lower"><aside><p class="eyebrow">正在聆听</p><h2>${selected.name}</h2><p>${selected.note}</p><canvas id="spectrum" width="300" height="58"></canvas><div class="player"><button id="play">▶</button><span>00:00</span><div></div><span>00:12</span><button id="stop">■</button></div></aside><section class="list"><div><p class="eyebrow">附近的声音</p><button>全部分类⌄</button></div>${places().map(p=>`<article data-id="${p.id}"><span class="dot ${p.category}"></span><div><b>${p.name}</b><small>${p.note}</small></div><time>${p.createdAt}</time></article>`).join('')}</section></section></main><dialog id="capture"><form method="dialog"><button class="close" value="cancel">×</button><p class="eyebrow">放置声音标记</p><h2>为这里留下些什么？</h2><label>地点名称<input id="name" placeholder="例如：胡同午后" required /></label><label>一段描述<input id="note" placeholder="记录你听到的声音" /></label><label>声音分类<select id="category"><option>生活</option><option>交通</option><option>自然</option><option>人声</option></select></label><div class="record"><button type="button" id="record">● 开始录音</button><label class="upload">上传音频<input id="upload" type="file" accept="audio/*"/></label><span id="audio-state">尚未添加声音</span></div><button class="save" value="default">保存到地图</button></form></dialog>`;bind()}
function open(){audioUrl=undefined;document.querySelector<HTMLDialogElement>('#capture')?.showModal()}
function bind(){spectrum=new Spectrum(document.querySelector('#spectrum')!);spectrum.idle();document.querySelectorAll<HTMLElement>('[data-id]').forEach(e=>e.onclick=()=>{selected=places().find(p=>p.id===e.dataset.id)!;render()});document.querySelector('.add')!.addEventListener('click',open);const map=document.querySelector('#map')!;map.onclick=e=>{if((e.target as HTMLElement).closest('.pin'))return;const r=map.getBoundingClientRect();pending={x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100};open()};document.querySelector('#play')!.addEventListener('click',()=>spectrum.play(selected.audioUrl));document.querySelector('#stop')!.addEventListener('click',()=>spectrum.stop());const d=document.querySelector<HTMLDialogElement>('#capture')!,rec=document.querySelector<HTMLButtonElement>('#record')!;rec.onclick=async()=>{try{if(recorder.isRecording()){audioUrl=URL.createObjectURL(await recorder.stop());rec.textContent='● 重新录音';document.querySelector('#audio-state')!.textContent='录音已添加'}else{await recorder.start();rec.textContent='■ 停止录音';document.querySelector('#audio-state')!.textContent='正在收音…'}}catch{document.querySelector('#audio-state')!.textContent='无法使用麦克风，请检查浏览器权限'}};document.querySelector<HTMLInputElement>('#upload')!.onchange=e=>{const f=(e.target as HTMLInputElement).files?.[0];if(f){audioUrl=URL.createObjectURL(f);document.querySelector('#audio-state')!.textContent=`已选择：${f.name}`}};d.querySelector('form')!.addEventListener('submit',e=>{if((e.submitter as HTMLButtonElement)?.value==='cancel')return;e.preventDefault();const name=document.querySelector<HTMLInputElement>('#name')!.value;if(!name)return;repo.save({id:crypto.randomUUID(),name,note:document.querySelector<HTMLInputElement>('#note')!.value||'一段新鲜的城市声音',category:document.querySelector<HTMLSelectElement>('#category')!.value as SoundCategory,x:pending.x,y:pending.y,createdAt:'刚刚',audioUrl});d.close();render()})}render()
